"""empty message

Revision ID: 207e5d742af4
Revises: bae22d34bb62
Create Date: 2022-02-20 11:51:35.535380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207e5d742af4'
down_revision = 'bae22d34bb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_member', sa.Column('requested_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_member', 'requested_message')
    # ### end Alembic commands ###
