"""empty message

Revision ID: 38f250ce0117
Revises: 835180f51d72
Create Date: 2022-02-26 12:25:23.081110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f250ce0117'
down_revision = '835180f51d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_message', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_message', sa.Column('message', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
