"""empty message

Revision ID: 42ce84481f92
Revises: 4c62267118c3
Create Date: 2022-02-20 10:48:21.452607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce84481f92'
down_revision = '4c62267118c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendship', 'user_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendship', 'user_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendship', 'user_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friendship', 'user_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
