"""empty message

Revision ID: 714092d5f95b
Revises: 06d4772e4c29
Create Date: 2022-02-26 12:24:42.997739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714092d5f95b'
down_revision = '06d4772e4c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_message', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_message', 'updated')
    # ### end Alembic commands ###
