"""empty message

Revision ID: 86602fc1b2b2
Revises: 42ce84481f92
Create Date: 2022-02-20 10:54:50.864061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86602fc1b2b2'
down_revision = '42ce84481f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('admin_1_id', sa.Integer(), nullable=False),
    sa.Column('admin_2_id', sa.Integer(), nullable=False),
    sa.Column('header_picture', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['admin_2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
