"""empty message

Revision ID: bae22d34bb62
Revises: c9b556b02999
Create Date: 2022-02-20 11:45:51.257195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bae22d34bb62'
down_revision = 'c9b556b02999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    op.add_column('group', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint('group_admin_1_id_fkey', 'group', type_='foreignkey')
    op.drop_constraint('group_admin_2_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['admin_id'], ['id'])
    op.drop_column('group', 'admin_2_id')
    op.drop_column('group', 'admin_1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin_1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('group', sa.Column('admin_2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_admin_2_id_fkey', 'group', 'user', ['admin_2_id'], ['id'])
    op.create_foreign_key('group_admin_1_id_fkey', 'group', 'user', ['admin_1_id'], ['id'])
    op.drop_column('group', 'admin_id')
    op.create_table('friendship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requested', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='friendship_friend_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='friendship_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='friendship_pkey')
    )
    # ### end Alembic commands ###
